#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs vela onto your system into ~/.local, making it available as ~/.local/bin/vela.

  Before running this you should ensure you have all the build dependencies installed with `./script/linux`.
  "
  exit 1
fi
export VELA_CHANNEL=$(<crates/vela/RELEASE_CHANNEL)
export VELA_UPDATE_EXPLANATION="You need to fetch and rebuild vela in $(pwd)"
script/bundle-linux

arch="$(uname -m)"
commit=$(git rev-parse HEAD | cut -c 1-7)
archive="vela-linux-${arch}.tar.gz"
export VELA_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
script/install.sh
